"""report.py: deterministic INDEX_REPORT.md generator, no LLM calls.

Every ranking is a stable sort with an id/path/name tie-break, so the same
DB always produces byte-identical Markdown. `subsystems` in config.json
unlocks named groups; without it, grouping falls back to top-level path.
"""
import argparse
from collections import Counter
from pathlib import Path

from chonks.core.config import load_config
from chonks.index.graph.pagerank import compute_pagerank_global
from chonks.storage.store import Store

TOP_GOD_NODES_OVERALL   = 15
TOP_GOD_NODES_SUBSYSTEM = 8
TOP_CONNECTIONS         = 8
NUM_QUESTIONS           = 5
# Generic infrastructure (Variant-like universal types, autogenerated binding
# roots, ...) excluded from question templating. Mirrors
# eval/relational_sample.py's hub-indegree-max default.
HUB_INDEGREE_MAX = 50


def _subsystem_for_path(path: str, subsystems: dict[str, list[str]]) -> str | None:
    """Longest-matching subsystem name for `path`, or None if no prefix
    matches. Kept local so report.py's import surface stays repomap/store only."""
    best: tuple[int, str] | None = None
    for name, prefixes in (subsystems or {}).items():
        for p in prefixes:
            if path.startswith(p) and (best is None or len(p) > best[0]):
                best = (len(p), name)
    return best[1] if best else None


def _group_for(path: str, subsystems: dict[str, list[str]]) -> str:
    """Community label used to detect cross-cutting edges/questions. Falls
    back to the top-level path segment when no subsystem prefix matches (or
    none are configured at all)."""
    if subsystems:
        s = _subsystem_for_path(path, subsystems)
        if s is not None:
            return s
    return path.split("/", 1)[0] or path


def _clean_name(name: str | None) -> bool:
    """Filters out short/synthetic names (operators, single letters, blanks)
    that make poor god-node/question subjects. Mirrors
    eval/relational_sample.py's clean_name."""
    return bool(name) and name[0].isalpha() and len(name) >= 3 and "operator" not in name


# ---------------------------------------------------------------------------
# God nodes
# ---------------------------------------------------------------------------

def _rank_nodes(chunks: list[dict], pagerank: dict[str, float], limit: int) -> list[dict]:
    ranked = sorted(
        chunks,
        key=lambda c: (-pagerank.get(c["id"], 0.0), c["path"], c["start_line"] or 0, c["id"]),
    )
    return ranked[:limit]


def _fmt_node(c: dict, pagerank: dict[str, float]) -> str:
    loc = f"{c['path']}:{c['start_line']}-{c['end_line']}"
    return (f"- **{c['name']}** ({c['chunk_type'] or 'unknown'}) — `{loc}` "
            f"— pagerank {pagerank.get(c['id'], 0.0):.4f}")


def _god_nodes_section(chunks: list[dict], pagerank: dict[str, float],
                        subsystems: dict[str, list[str]]) -> str:
    lines = ["## God nodes", "",
              "Highest-PageRank symbols overall — the structural core of the codebase.", ""]
    top = _rank_nodes(chunks, pagerank, TOP_GOD_NODES_OVERALL)
    lines += [_fmt_node(c, pagerank) for c in top] if top else ["_No named symbols indexed._"]

    if subsystems:
        by_group: dict[str, list[dict]] = {}
        for c in chunks:
            by_group.setdefault(_group_for(c["path"], subsystems), []).append(c)
        lines += ["", "### Per subsystem"]
        for name in sorted(by_group):
            lines += ["", f"#### {name}", ""]
            top_sub = _rank_nodes(by_group[name], pagerank, TOP_GOD_NODES_SUBSYSTEM)
            lines += [_fmt_node(c, pagerank) for c in top_sub] if top_sub else ["_No named symbols._"]
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Surprising connections
# ---------------------------------------------------------------------------

def _connections_section(chunks_by_id: dict[str, dict], typed_refs: list[tuple[str, str, str]],
                          pagerank: dict[str, float], subsystems: dict[str, list[str]]) -> str:
    def weight(u: str, v: str) -> float:
        return pagerank.get(u, 0.0) + pagerank.get(v, 0.0)

    # Cross-language edges: 'xlang' is recorded symmetrically (u->v and v->u)
    # by index.graph.refs._build_graph, so canonicalize on the sorted id pair to
    # report each crossing once.
    xlang_pairs: dict[tuple[str, str], float] = {}
    for u, v, et in typed_refs:
        if et != "xlang" or u not in chunks_by_id or v not in chunks_by_id:
            continue
        pair = (u, v) if u < v else (v, u)
        w = weight(u, v)
        if pair not in xlang_pairs or w > xlang_pairs[pair]:
            xlang_pairs[pair] = w
    ranked_xlang = sorted(xlang_pairs.items(), key=lambda kv: (-kv[1], kv[0]))[:TOP_CONNECTIONS]

    lines = ["## Surprising connections", "", "### Cross-language edges", ""]
    if not ranked_xlang:
        lines.append("_None detected._")
    else:
        for (u, v), w in ranked_xlang:
            a, b = chunks_by_id[u], chunks_by_id[v]
            lines.append(f"- **{a['name']}** (`{a['path']}`, {a['language'] or '?'}) "
                         f"↔ **{b['name']}** (`{b['path']}`, {b['language'] or '?'}) — weight {w:.4f}")

    # Excludes 'mentions'/'associated' refs: those are still name
    # co-occurrence, not a real dependency (see index.graph.refs.build_refs'
    # associated_top_frac).
    cross_group = []
    for u, v, et in typed_refs:
        if et in ("mentions", "associated") or u not in chunks_by_id or v not in chunks_by_id:
            continue
        gu = _group_for(chunks_by_id[u]["path"], subsystems)
        gv = _group_for(chunks_by_id[v]["path"], subsystems)
        if gu != gv:
            cross_group.append((u, v, et, weight(u, v), gu, gv))
    cross_group.sort(key=lambda t: (-t[3], t[2], t[0], t[1]))

    lines += ["", "### Cross-subsystem edges", ""]
    if not cross_group:
        lines.append("_None detected._")
    else:
        for u, v, et, w, gu, gv in cross_group[:TOP_CONNECTIONS]:
            a, b = chunks_by_id[u], chunks_by_id[v]
            lines.append(f"- **{a['name']}** (`{gu}`) --{et}--> **{b['name']}** (`{gv}`) — weight {w:.4f}")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Suggested questions
# ---------------------------------------------------------------------------

def _suggested_questions(chunks_by_id: dict[str, dict], typed_refs: list[tuple[str, str, str]],
                          pagerank: dict[str, float], subsystems: dict[str, list[str]],
                          limit: int = NUM_QUESTIONS) -> str:
    out_edges: dict[str, set[str]] = {}
    indegree: Counter = Counter()
    for u, v, _et in typed_refs:
        out_edges.setdefault(u, set()).add(v)
        indegree[v] += 1

    candidates = [c for c in chunks_by_id.values() if _clean_name(c["name"]) and c["id"] in out_edges]
    candidates.sort(key=lambda c: (-pagerank.get(c["id"], 0.0), c["path"], c["id"]))

    lines = ["## Suggested questions", "",
              "Templated from high-centrality symbols with cross-subsystem neighbours "
              "— a starting point for exploring what this index connects.", ""]
    used_paths: set[str] = set()
    count = 0
    for a in candidates:
        if count >= limit:
            break
        if a["path"] in used_paths:
            continue
        own_group = _group_for(a["path"], subsystems)
        neighbour_groups: Counter = Counter()
        for nid in sorted(out_edges.get(a["id"], ())):
            n = chunks_by_id.get(nid)
            if not n or not _clean_name(n["name"]) or n["name"] == a["name"]:
                continue
            if indegree.get(nid, 0) > HUB_INDEGREE_MAX:
                continue
            g = _group_for(n["path"], subsystems)
            if g != own_group:
                neighbour_groups[g] += 1
        if not neighbour_groups:
            continue
        target_group = min(neighbour_groups.items(), key=lambda kv: (-kv[1], kv[0]))[0]
        count += 1
        lines.append(f"{count}. How does **{a['name']}** (`{a['path']}`) work, "
                     f"and how does it interact with `{target_group}`?")
        used_paths.add(a["path"])

    if count == 0:
        lines.append("_Not enough cross-subsystem structure to template questions from._")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Vitals footer
# ---------------------------------------------------------------------------

def _vitals_section(store: Store) -> str:
    stats = store.stats()
    langs = store.language_counts()
    parsed = store.parsed_file_count()
    total_files = stats["files"]
    lang_line = ", ".join(
        f"{lang or 'unknown'}: {n}" for lang, n in sorted(langs.items(), key=lambda kv: (-kv[1], kv[0] or ""))
    ) or "none"
    health_pct = (100.0 * parsed / total_files) if total_files else 0.0
    return "\n".join([
        "## Index vitals", "",
        f"- **Files**: {total_files}",
        f"- **Chunks**: {stats['chunks']}",
        f"- **Languages** (by chunk count): {lang_line}",
        f"- **Parse health**: {parsed}/{total_files} files produced at least one chunk ({health_pct:.1f}%)",
    ]).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------

def _header(store: Store, config: dict, db_path: str) -> str:
    stats = store.stats()
    root = config.get("codebase") or stats.get("indexed_root") or db_path
    name = Path(root).name or root
    return f"# INDEX_REPORT: {name}\n\n_Root: `{root}`_\n"


def build_report(store: Store, config: dict, db_path: str) -> str:
    subsystems = config.get("subsystems") or {}
    pagerank = compute_pagerank_global(store)
    chunks = store.get_named_chunks_meta()
    chunks_by_id = {c["id"]: c for c in chunks}
    typed_refs = store.get_all_refs_typed()

    sections = [
        _header(store, config, db_path),
        _god_nodes_section(chunks, pagerank, subsystems),
        _connections_section(chunks_by_id, typed_refs, pagerank, subsystems),
        _suggested_questions(chunks_by_id, typed_refs, pagerank, subsystems),
        _vitals_section(store),
    ]
    return "\n".join(sections).rstrip() + "\n"


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", default=None, help="Path to chunks DB (default: config.json's `db` key)")
    ap.add_argument("--config", default=None, help="Path to config.json (default: the first of ./config.json, ./chonks/config.json, ./.chonks.json that is present)")
    ap.add_argument("-o", "--out", default="INDEX_REPORT.md", help="Output Markdown path")
    args = ap.parse_args(argv)

    loaded = load_config(args.config)
    if loaded.problems:
        problem = loaded.problems[0]
        ap.error(f"config not readable: {problem.path}: {problem.reason}")
    config = loaded.data
    # CLI flag overrides config key, same precedence as chunker/serve.
    args.db = args.db or config.get("db")
    if not args.db:
        ap.error("--db required (or set `db` in config.json)")
    if not Path(args.db).exists():
        ap.error(f"DB not found: {args.db} (run chonks index first)")
    store = Store(Path(args.db))
    try:
        report = build_report(store, config, args.db)
    finally:
        store.close()

    # Explicit UTF-8: the report contains non-ASCII glyphs (↔, ·) and
    # Windows' default locale codec (cp1252) can't encode them.
    Path(args.out).write_text(report, encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
